#ifndef _CHASSIS_TASK_H
#define _CHASSIS_TASK_H

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"
#include "stdint.h"

// 抬升角度环
#define OUTPUT_LIFT 3
#define INTERLIMIT_LIFT 0
#define DEBAND_LIFT 0
#define KP_LIFT 0.5
#define KI_LIFT 0
#define KD_LIFT 0

//抬升前进
#define OUTPUT_LIFT_MOVE 10000
#define INTERLIMIT_LIFT_MOVE 0
#define DEBAND_LIFT_MOVE 1
#define KP_LIFT_MOVE 12
#define KI_LIFT_MOVE 0.8
#define KD_LIFT_MOVE 0

// 底盘pid
#define OUTPUT_CHASSIS_3508 16384
#define INTERLIMIT_CHASSIS_3508 2000
#define DEBAND_CHASSIS_3508 1
#define KP_CHASSIS_3508 15
#define KI_CHASSIS_3508 0.8
#define KD_CHASSIS_3508 0

// 底盘整体
#define OUTPUT_CHASSIS_LINEAR 6
#define INTERLIMIT_CHASSIS_LINEAR 0
#define DEBAND_CHASSIS_LINEAR 0
#define KP_CHASSIS_LINEAR 20
#define KI_CHASSIS_LINEAR 0
#define KD_CHASSIS_LINEAR 0

#define OUTPUT_CHASSIS_ANGLE 16384
#define INTERLIMIT_CHASSIS_ANGLE 500000
#define DEBAND_CHASSIS_ANGLE 500
#define KP_CHASSIS_ANGLE 10
#define KI_CHASSIS_ANGLE 0
#define KD_CHASSIS_ANGLE 1

//对接角度环
#define OUTPUT_CHASSIS_TRACK 0.05
#define INTERLIMIT_CHASSIS_TRACK 0
#define DEBAND_CHASSIS_TRACK 0
#define KP_CHASSIS_TRACK 0.04
#define KI_CHASSIS_TRACK 0
#define KD_CHASSIS_TRACK 0

#ifdef __cplusplus
}
#endif

#endif
